### ISSUE TITLE
Problem Thematic Data Url

### ISSUE THREAD

**Issue by gustavo1976** [3dcitydb/tutorials#4]
I follow the tutorial and it works, but I'm trying to use the example KmlManhattanExample to add the thematic data url but this data doesn't appear in the window when you click in an object., I don't know what I'm doing bad.
buildingLayer = new CitydbKmlLayer({
        url: 'Datos/ConTexturas/Berlin_con_collada_MasterJSON.json',
        name: 'LOD2',
        layerDataType:'COLLADA/KML/glTF',
        layerProxy: false,
        layerClampToGround: true,
        gltfVersion: 2.0,
        thematicDataUrl: 'https://docs.google.com/spreadsheets/d/1oNq3mHXYJIzVg5VLIclLfVKvaE2QByBq/edit?usp=sharing&ouid=110216278049333696593&rtpof=true&sd=true',
        thematicDataSource: 'GoogleSheets',
        tableType: 'Horizontal',
        cityobjectsJsonUrl: 'Datos/ConTexturas/Berlin_con.json',
        minLodPixels: '',
        maxLodPixels: '',
        maxSizeOfCachedTiles: 200,
        maxCountOfVisibleTiles: 200
}
    );

![image](https://user-images.githubusercontent.com/43615415/200308081-bb6f6778-db98-45cc-b14e-74b65acaeeb9.png)

**Comment by Son-HNguyen** [comment]
Hi, can you see in developer mode in your browser if there is any error?

**Comment by gustavo1976** [comment]
I modify de .htaccess adding 
<IfModule mod_headers.c>
       Header set Access-Control-Allow-Origin "*"
</IfModule>
and there is no error in console, I upload the file to my server in the web https://apartamentosentrecolumnas.com/visor/index22.html and in both cases it doesn't show information

**Comment by Son-HNguyen** [comment]
Yes, if it's CORS then you might need that header in `.htaccess` in your https client. Where is the URL of the spreadsheet entered in your code?

**Comment by gustavo1976** [comment]
Its on thematicdataurl option when I define the building layer.
buildingLayer = new CitydbKmlLayer({
url: 'Datos/ConTexturas/Berlin_con_collada_MasterJSON.json',
name: 'LOD2',
layerDataType:'COLLADA/KML/glTF',
layerProxy: false,
layerClampToGround: true,
gltfVersion: 2.0,
thematicDataUrl: 'https://docs.google.com/spreadsheets/d/1oNq3mHXYJIzVg5VLIclLfVKvaE2QByBq/edit?usp=sharing&ouid=110216278049333696593&rtpof=true&sd=true',

**Comment by Son-HNguyen** [comment]
It seems either the options for `thematicDataSource` and `tableType` are missing in your `options` or the fetching for information from the spreadsheets was not called at all.

**Comment by gustavo1976** [comment]
Yes I have them puts, I dont put allí the options because I puts It on the first post, allí the options I use are:
buildingLayer = new CitydbKmlLayer({
url: 'Datos/ConTexturas/Berlin_con_collada_MasterJSON.json',
name: 'LOD2',
layerDataType:'COLLADA/KML/glTF',
layerProxy: false,
layerClampToGround: true,
gltfVersion: 2.0,
thematicDataUrl: 'https://docs.google.com/spreadsheets/d/1oNq3mHXYJIzVg5VLIclLfVKvaE2QByBq/edit?usp=sharing&ouid=110216278049333696593&rtpof=true&sd=true',
thematicDataSource: 'GoogleSheets',
tableType: 'Horizontal',
cityobjectsJsonUrl: 'Datos/ConTexturas/Berlin_con.json',
minLodPixels: '',
maxLodPixels: '',
maxSizeOfCachedTiles: 200,
maxCountOfVisibleTiles: 200
}
);

**Comment by Son-HNguyen** [comment]
These options look good to me. Can you point to where in your codes in https://apartamentosentrecolumnas.com/visor/ (which JS file) you entered these in, since this is your customized implementation it seems?

**Comment by gustavo1976** [comment]
I downloaded the tutorial and followed it. I took the example that it brings from Berlin and added the thematic data url but it doesn't work. I don't have a custom js file, I insert it in the index.html, all the code I have put it's:






  | <script>

  |  
  | // URL controller
  | var urlController = new UrlController();
  |  
  | Cesium.Ion.defaultAccessToken = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzMGM4OGM5Zi00OWNiLTQ1ZjEtODRiMi01M2YwYTA4MzY5NzYiLCJpZCI6MTEyMzk2LCJpYXQiOjE2NjY2OTgyODN9.LEWMTUgb6ngjAFOBnu68oGAbv9YoEgax9x8jhKINzvc';
  |  
  | var viewer = new Cesium.Viewer('cesiumContainer', {
  | baseLayerPicker: false
  | });
  | var extent = new Cesium.Rectangle.fromDegrees(13.381455644224731,52.532437942637095,13.401939576596078,52.54451129257474);
  | viewer.camera.setView({destination: extent})
  |  
  | var webMap = new WebMap3DCityDB(viewer);
  |  
  | // activate Events
  | webMap.activateViewChangedEvent(true);
  | webMap.activateMouseClickEvents(true);
  | webMap.activateMouseMoveEvents(true);
  |  
  | var buildingLayer;
  |  
  | const options = {
  | url: 'Datos/ConTexturas/Berlin_con_collada_MasterJSON.json',
  | name: 'LOD2',
  | layerDataType:'',
  | layerProxy: false,
  | layerClampToGround: true,
  | gltfVersion: '',
  | thematicDataUrl: 'https://docs.google.com/spreadsheets/d/1oNq3mHXYJIzVg5VLIclLfVKvaE2QByBq/edit?usp=share_link&ouid=110216278049333696593&rtpof=true&sd=true',
  | thematicDataSource: '',
  | tableType: '',
  | cityobjectsJsonUrl: 'Datos/ConTexturas/Berlin_con.json',
  | minLodPixels: '',
  | maxLodPixels: '',
  | maxSizeOfCachedTiles: 200,
  | maxCountOfVisibleTiles: 200
  | }
  |  
  | buildingLayer = new CitydbKmlLayer(options);
  |  
  | var promise = webMap.addLayer(buildingLayer);
  | Cesium.when(promise, function (loadedcitydbLayer) {
  | loadedcitydbLayer.zoomToStartPosition();
  | //loadedcitydbLayer.dataSourceController = new DataSourceController(loadedcitydbLayer.thematicDataSource, signInController, options);
  | });
  |  
  | // Cesium.GeoJsonDataSource('https://docs.google.com/spreadsheets/d/1oNq3mHXYJIzVg5VLIclLfVKvaE2QByBq');
  | // Sign in utilities
  | var googleClientId = urlController.getUrlParaValue('googleClientId', window.location.href, CitydbUtil);
  | if (googleClientId) {
  | var signInController = new SigninController(googleClientId);
  | }

  | </script>
 

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by Son-HNguyen** [comment]
I've just created a web client on our website using your data:
https://www.3dcitydb.org/3dcitydb-web-map/1.9.0/3dwebclient/index.html?t=3DCityDB-Web-Map-Client&s=false&ts=0&la=52.534103&lo=13.392796&h=612.937&hd=6&p=-50&r=0&l_0=u%3Dhttps%253A%252F%252Fapartamentosentrecolumnas.com%252Fvisor%252FDatos%252FConTexturas%252FBerlin_con_collada_MasterJSON.json%26n%3DLOD2%26ld%3DCOLLADA%252FKML%252FglTF%26lp%3Dfalse%26lc%3Dtrue%26gv%3D2.0%26a%3Dtrue%26tdu%3Dhttps%253A%252F%252Fdocs.google.com%252Fspreadsheets%252Fd%252F1oNq3mHXYJIzVg5VLIclLfVKvaE2QByBq%252Fedit%253Fusp%253Dsharing%2526ouid%253D110216278049333696593%2526rtpof%253Dtrue%2526sd%253Dtrue%26ds%3DGoogleSheets%26tt%3DHorizontal%26gc%3Dhttps%253A%252F%252Fapartamentosentrecolumnas.com%252Fvisor%252FDatos%252FConTexturas%252FBerlin_con.json%26il%3D120%26al%3D1.7976931348623157e%252B308%26ac%3D200%26av%3D200&sw=showOnStart%3Dfalse

It works fine as well as I can tell. I'm guessing either you did not call the function to fetch data from the Google Spreadsheets correctly or not at all, or your server is configured incorrectly.

**Comment by gustavo1976** [comment]
I have solved it by modifyin this lines from Cesium.when(promise...
    Cesium.when(promise, function (loadedcitydbLayer) {
        loadedcitydbLayer.zoomToStartPosition();
        //To See the data of the buildings.
        var optionsThematic = getDataSourceControllerOptions(loadedcitydbLayer);
        loadedcitydbLayer.dataSourceController = new DataSourceController(loadedcitydbLayer.thematicDataSource, signInController, optionsThematic);
        addEventListeners(loadedcitydbLayer);
    });
and adding this to my index.html from the script.js

function getDataSourceControllerOptions(layer) {

    var dataSourceUri = layer.thematicDataUrl === "" ? layer.url : layer.thematicDataUrl;
    var options = {
        uri: dataSourceUri,
        tableType: layer.tableType,
        thirdPartyHandler: {
            type: "Cesium",
            handler: layer ? layer._citydbKmlDataSource : undefined
        },
        clientId: googleClientId ? googleClientId : "",
        proxyPrefix: layer.layerProxy ? CitydbUtil.getProxyPrefix(dataSourceUri) : ""
    };
    return options;
}
var clickedEntities = {};
function addEventListeners(layer) {

    function auxClickEventListener(object) {
        var objectId;
        var targetEntity;
        if (layer instanceof CitydbKmlLayer) {
            targetEntity = object.id;
            objectId = targetEntity.name;
        } else if (layer instanceof Cesium3DTilesDataLayer) {
            console.log(object);
            if (!(object._content instanceof Cesium.Batched3DModel3DTileContent))
                return;

            var featureArray = object._content._features;
            if (!Cesium.defined(featureArray))
                return;
            var objectId = featureArray[object._batchId].getProperty("id");
            if (!Cesium.defined(objectId))
                return;

            targetEntity = new Cesium.Entity({
                id: objectId
            });
            cesiumViewer.selectedEntity = targetEntity;
        }

        // Save this clicked object for later use (such as zooming using ID)
        clickedEntities[objectId] = targetEntity;

        return [objectId ,targetEntity];
    }

    layer.registerEventHandler("CLICK", function (object) {
        var res = auxClickEventListener(object);
        createInfoTable(res, layer);
    });

    layer.registerEventHandler("CTRLCLICK", function (object) {
        auxClickEventListener(object);
    });
}
function createInfoTable(res, citydbLayer) {

    //var thematicDataSourceDropdown = document.getElementById("thematicDataSourceDropdown");
    var selectedThematicDataSource = 'GoogleSheets';//thematicDataSourceDropdown.options[thematicDataSourceDropdown.selectedIndex].value;

    var gmlid = selectedThematicDataSource === "KML" ? res[1]._id : res[0];
    var cesiumEntity = res[1];

    var thematicDataUrl = citydbLayer.thematicDataUrl;
    cesiumEntity.description = "Loading feature information...";

    citydbLayer.dataSourceController.fetchData(gmlid, function (kvp) {
        if (!kvp) {
            cesiumEntity.description = 'No feature information found';
        } else {
            console.log(kvp);
            var html = '<table class="cesium-infoBox-defaultTable" style="font-size:10.5pt"><tbody>';
            for (var key in kvp) {
                var iValue = kvp[key];
                // check if this value is a valid URL
                if (isValidUrl(iValue)) {
                    iValue = '<a href="' + iValue + '" target="_blank">' + iValue + '</a>';
                }
                html += '<tr><td>' + key + '</td><td>' + iValue + '</td></tr>';
            }
            html += '</tbody></table>';

            cesiumEntity.description = html;
        }
    }, 1000, cesiumEntity);

}
function isValidUrl(str) {
    regexp =  /^(?:(?:https?|ftp):\/\/)?(?:(?!(?:10|127)(?:\.\d{1,3}){3})(?!(?:169\.254|192\.168)(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)(?:\.(?:[a-z\u00a1-\uffff0-9]-*)*[a-z\u00a1-\uffff0-9]+)*(?:\.(?:[a-z\u00a1-\uffff]{2,})))(?::\d{2,5})?(?:\/\S*)?$/;
    return regexp.test(str);
}

**Comment by Son-HNguyen** [comment]
Great that you solved it! The code that you were using might be old. The latest version of the web map client can be found here:
https://github.com/3dcitydb/3dcitydb-web-map

**Comment by gustavo1976** [comment]
Thanks I'll test It.
